### ISSUE TITLE
E2E Test Integration

### ISSUE THREAD

**Issue by sgtran1** [cse110-sp24-group17/cse110-sp24-group17#1]
-integrate E2E test integrations

**Comment by ryanliulwy** [comment]
Create end-to-end tests to simulate a user's workflow on the webpage from start to finish. Create an environment to simulate user actions (i.e. using Jest Puppeteer) and test for expected webpage behavior. Integrate tests to automatically run at pull requests / merges.
- Create a list of user actions to test
- Create corresponding list of expected outcomes
- Implement simulation of user actions
- Test simulated outcome against expected outcome
