### ISSUE TITLE
Unit Test Integration

### ISSUE THREAD

**Issue by sgtran1** [cse110-sp24-group17/cse110-sp24-group17#2]
- implement JEST unit testing

**Comment by ryanliulwy** [comment]
Create unit tests to check internal software functionality and correctness Integrate tests to automatically run at pull requests / merges.
- Identify functions and their expected behaviors
- For each function, create a few tests to test functionality under different circumstances
- Aim for high total code coverage through tests (by lines of code, at least ~80% coverage)
