### ISSUE TITLE
Bug: Daily Journal render in Project Views

### ISSUE THREAD

**Issue by ryanliulwy** [cse110-sp24-group17/cse110-sp24-group17#82]
When a user creates a file by using the Daily Journal for a date, a new file is added to the "Daily Journal" folder in Project Views. The file exists and is stored in local storage, but the file name will not render under the Project Views tab until another non-journal file is created. 
- Re-render the project view page when a new journal entry is created to properly display its file name

Assigned to Jacob, complete by 6/5/24

**Comment by sunho** [comment]
Fixed by #87
